name: First Workflow
on: workflow_dispatch
jobs:
  first_job:
    name: First job with 2 printing 
    runs-on: ubuntu-latest
    steps:
    
      - name: "Print greeting"
        run: echo "Hello world"
      
      - name: "Print goodbye"
        run: echo "Goodbye"
